### ISSUE TITLE
PHP 8.1 

### ISSUE THREAD

**Issue by umax-imagination-media** [pepperjam/ascend-magento2-extension#2]
Hello @robr3rd , @pepperjam-admin  do you have any ETA on PHP 8.1 support for your extension?

Currently [UCT](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/upgrade-compatibility-tool/overview.html) is showing 26 errors in your extension.  
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/108946938/184074457-5063806e-3538-4485-b788-d5f7c0f2de7c.png">

**Comment by dmirulescu** [comment]
@umax-imagination-media thanks for reporting, we'll appreciate if you can post the detailed report from UCT so we can clear all warnings. 
[v1.5.1](https://github.com/pepperjam/ascend-magento2-extension/releases/tag/1.5.1) should work with php8.1
