### ISSUE TITLE
Error PHP 8.1 : Deprecated Functionality: trim()

### ISSUE THREAD

**Issue by aelmizeb** [pepperjam/ascend-magento2-extension#3]
Hello there;

We are working on the magento upgrade for 2.4.5 and we have this error on your module. We are on PHP 8.1.

`1 exception(s):
Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/pepperjam/network-magento2-module/Model/Beacon.php on line 46

Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/pepperjam/network-magento2-module/Model/Beacon.php on line 46
<pre>#1 trim() called at [vendor/pepperjam/network-magento2-module/Model/Beacon.php:46]
#2 Pepperjam\Network\Model\Beacon->getCouponCode() called at [vendor/pepperjam/network-magento2-module/Model/Beacon/Itemized.php:19]
#3 Pepperjam\Network\Model\Beacon\Itemized->getUrl() called at [vendor/pepperjam/network-magento2-module/Block/Checkout/Onepage/Beacon.php:40]
#4 Pepperjam\Network\Block\Checkout\Onepage\Beacon->getBeaconUrl() called at [vendor/pepperjam/network-magento2-module/view/frontend/templates/checkout/onepage/beacon.phtml:1]
#5 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#6 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#7 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]`

Can you please take a look to this error ? if you have a patch or a new version of the module for it please share it with us.

**Comment by dmirulescu** [comment]
@aelmizeb this is fixed with [v1.5.1](https://github.com/pepperjam/ascend-magento2-extension/releases/tag/1.5.1)
