### ISSUE TITLE
Would you enhance security issue on Controller/Adminhtml/Domain/Validate.php

### ISSUE THREAD

**Issue by ph4mHoa** [pepperjam/ascend-magento2-extension#4]
The code still relies on user input from `$this->getRequest()->getParam('url')` to construct the $domain variable, which is then used in the cURL request. Even if the user needs an admin account, lack of proper input validation and sanitization can still open the door for potential SSRF attacks.

Would you enhance this by Regex-based Validation : use regular expressions to validate the input domain against a specific pattern or set of rules
or 
use Third-Party Domain Validation Service please

**Comment by dmirulescu** [comment]
@ph4mHoa thanks for reporting this, it will be taken care of.

**Comment by dmirulescu** [comment]
Solved with v1.5.3
