### ISSUE TITLE
Not compatible with 2.4.7-p3

### ISSUE THREAD

**Issue by dangtrinhtran** [pepperjam/ascend-magento2-extension#5]
Hello,

Magento 2.4.7-p3 and pepperjam/network-magento2-module 1.5.5

Then go to admin and edit a product, we will get this.

`Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Pepperjam\Network\Model\Config\Source\CommissioningCategory::$storeManager is deprecated in vendor/pepperjam/network-magento2-module/Model/Config/Source/CommissioningCategory.php on line 17`

**Comment by dmirulescu** [comment]
Hi @dangtrinhtran thank you for your reporting. Could you please point out your php version and the error_reporting setup?

**Comment by dangtrinhtran** [comment]
Hi @dmirulescu 

We are on PHP 8.3. We created a patch for this

<img width="1250" alt="Screenshot 2024-12-17 at 9 40 59 AM" src="https://github.com/user-attachments/assets/25cf4e47-1cd1-4c0b-9ebe-fa96ad2a494d" />

**Comment by dmirulescu** [comment]
Thanks @dangtrinhtran I pushed it as 1.5.6 release.
